### ISSUE TITLE
curl: (3) Illegal characters found in URL

### ISSUE THREAD

**Issue by changeme** [ameer1234567890/tinifier#1]
Hi.
I got this message when I try to run 

`~/scripts/tinifier$ ./tinifier.sh 
[17:07:42] [INFO] Starting compression....
[17:07:42] [INFO] Compressing "DSC08310.JPG".... (3.56 MB) (1 of 1)
######################################################################## 100.0%
/50007:46] [INFO] Total API Requests: 4
curl: (3) Illegal characters found in URL
stat: cannot stat 'compressed/DSC08310.JPG': No such file or directory
[17:07:46] [INFO] Done compressing "DSC08310.JPG" (0 KB)

[17:07:46] [INFO] Re-try 1
[17:07:46] [INFO] Compressing "DSC08310.JPG".... (3.56 MB) (1 of 1)
######################################################################## 100.0%
`

**Comment by ameer1234567890** [comment]
Seems like you deleted/moved the source files while it was running.

**Comment by NathanaelA** [comment]
@ameer1234567890 - I had the same thing occur -- the issue isn't `deleted/moved` file.

The issue is this line here: https://github.com/ameer1234567890/tinifier/blob/master/tinifier.sh#L59

`download_url="$(grep <api_response.txt location | awk '{print $2}')"` 
Needs to be:
`download_url="$(grep <api_response.txt location | awk '{print $2}')" | sed 's/\r//g'`

For some reason awk/grep; is keeping the trailing ^M  (i.e. \r) ; so it has to be stripped out also; otherwise `curl` throws the invalid character..   The additional `| sed 's/\r//g'` strips it out if it is present.

**Comment by ameer1234567890** [comment]
I am unable to reproduce this issue. However, this could be an anormally with the awk version that you use. Which OS are you running this on?

**Comment by NathanaelA** [comment]
I'm running this on Mint 19.1  (Which is based on Ubuntu Bionic)
Awk - GNU Awk 4.1.4, API: 1.1 (GNU MPFR 4.0.1, GNU MP 6.1.2)
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1c zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
grep (GNU grep) 3.1

The only way I was able to discover the ^M was by doing a `echo $download_url>output.txt` and then opening that up with a editor...   Honestly don't know what is adding it; but stripping it was what was needed...
